name: .NET Core CI/CD

on:
  push:
    branches:
      - main  # Запускать процесс при пуше в основную ветку
  pull_request:
    branches:
      - main  # Запускать процесс при создании PR в основную ветку

jobs:
  build:
    runs-on: ubuntu-latest  # Используем Ubuntu для выполнения CI/CD

    steps:
    - name: Check out code
      uses: actions/checkout@v2  # Получаем код из репозитория

    - name: Set up .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '9.0'  # Укажи нужную версию .NET

    - name: Restore dependencies
      run: dotnet restore  # Восстанавливаем зависимости

    - name: Build the project
      run: dotnet build --configuration Release  # Сборка проекта в режиме Release

    - name: Run tests
      run: dotnet test --no-build --verbosity normal  # Запуск тестов

    - name: Publish the app
      run: dotnet publish --configuration Release --output ./publish  # Публикация приложения

    - name: Deploy to server or cloud (опционально)
      run: echo "Deploying application"  # Здесь можно добавить шаги для деплоя